{% set name = "pycuda" %}
{% set version = "2021.1" %}
{% set sha256 = "ab87312d0fc349d9c17294a087bb9615cffcf966ad7b115f5b051008a48dd6ed" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 7
  skip: true  # [cuda_compiler_version in (undefined, "None")]
  missing_dso_whitelist:
    - "*/libcuda.*"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}

  host:
    - python
    - pip
    - boost-cpp
    - numpy

  run:
    - python
    - boost-cpp
    - {{ pin_compatible('numpy') }}
    - pytools >=2011.2
    - decorator >=3.2.0
    - appdirs >=1.4.0
    - mako

test:
  requires:
    - pytest >=2
  source_files:
    - test

about:
  home: http://pypi.python.org/pypi/pycuda
  doc_url: https://documen.tician.de/pycuda
  dev_url: http://github.com/inducer/pycuda
  license: MIT
  license_file: LICENSE
  summary: Python wrapper for CUDA
  description: |
      PyCUDA lets you access GPUs from Python, through the CUDA parallel
      compute interface.
        
extra:
  recipe-maintainers:
    - inducer
